Repository co-demos/ApiViz, pull requests merged in 2019-02, with the labels that each got.

#19 update README + adding GUIDELINE_DEV.md
  GUIDELINES_DEV.md
  README.md
Labels: codeReview

#23 add static/build folder
  .gitignore
  app/frontend/package-lock.json
  app/frontend/package.json
  app/static/build/Readme.md
Labels: bug

#29 modif de views.py
  app/frontend/scripts/routes/searchRoutes.js
  app/frontend/scripts/routes/userRoutes.js
  app/views.py
Labels: enhancement

#32 updating the config data models by default
  README.md
  app/api/__init__.py
  app/config_app/config_app_data_endpoints.py
  app/config_app/config_app_data_styles.py
  app/config_app/config_app_global.py
  app/config_app/config_app_routes.py
  app/config_app/config_app_socials.py
  app/config_app/config_env.py
  app/config_app/config_secret_vars_example.py
  app/views.py
  requirements.txt
  run_apiviz.py
Labels: XS, backoffice, codeReview, enhancement
