Repository co-demos/ApiViz, pull requests merged in 2019-03, with the labels that each got.

#48 J cleanappconfig
  app/__init__.py
  app/config_app/config_app_routes.py
  app/config_app/config_env.py
  app/config_app/config_secret_vars_example.py
Labels: codeReview

#51 adding lot of config options for routes and global UI
  CHANGELOG.md
  app/api/__init__.py
  app/config_app/app_metas.py
  app/config_app/config_app_data_endpoints.py
  app/config_app/config_app_data_styles.py
  app/config_app/config_app_footer.py
  app/config_app/config_app_global.py
  app/config_app/config_app_navbar.py
  app/config_app/config_app_routes.py
  app/config_app/config_app_socials.py
  app/config_app/config_app_styles.py
  app/config_app/config_env.py
  app/templates/footer.html
  app/views.py
Labels: XS, codeReview

#52 simplifying contents_fields in routes
  app/config_app/config_app_footer.py
  app/config_app/config_app_routes.py
Labels: codeReview

#49 G routes4
  app/config_app/config_app_data_endpoints.py
  app/config_app/config_app_routes.py
  app/config_app/config_app_styles.py
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/scripts/cisProjectSearchAPI.js
  app/frontend/scripts/components/DynamicDetail.vue
  app/frontend/scripts/components/DynamicList.vue
  app/frontend/scripts/components/DynamicMap.vue
  app/frontend/scripts/components/DynamicSearchScreenSqueleton.vue
  app/frontend/scripts/components/ProjectCard.vue
  app/frontend/scripts/components/SearchResultsList.vue
  app/frontend/scripts/components/screens/DynamicScreen.vue
  app/frontend/scripts/components/screens/SearchListScreen.vue
  app/frontend/scripts/components/screens/SearchMapScreen.vue
  app/frontend/scripts/main.js
  app/frontend/scripts/routes/dynamicRoutes.js
  app/frontend/scripts/routes/main.js
  app/frontend/scripts/routes/searchRoutes.js
  app/frontend/scripts/routes/userRoutes.js
  app/frontend/scripts/store.js
  app/frontend/scripts/store/actions.js
  app/frontend/scripts/store/getters.js
  app/frontend/scripts/store/mutations.js
  app/frontend/scripts/store/store.js
  app/frontend/scripts/utils.js
  app/templates/footer.html
  app/templates/new-home.html
  app/templates/spa.html
  app/views.py
Labels: M, codeReview

#53 J teststatic
  app/frontend/package-lock.json
  app/frontend/scripts/components/CISSearchResultsCountAndTabs.vue
  app/frontend/scripts/components/DynamicDetail.vue
  app/frontend/scripts/components/DynamicSearchScreenSqueleton.vue
  app/frontend/scripts/components/ProjectCard.vue
  app/frontend/scripts/components/SearchScreenSqueleton.vue
  app/frontend/scripts/components/SearchWithFilters.vue
  app/frontend/styles/apiviz-colors.scss
  app/frontend/styles/apiviz-misc.scss
  app/frontend/styles/apiviz-spacing.scss
  app/frontend/styles/cis-colors.scss
  app/frontend/styles/cis-misc.scss
  app/frontend/styles/cis-spacing.scss
  app/frontend/styles/commons.scss
  app/frontend/styles/custom-bulma.scss
  app/frontend/styles/home.scss
  app/frontend/styles/http-errors.scss
  app/frontend/styles/le-collectif.scss
  app/frontend/styles/le-projet.scss
  app/frontend/styles/main.scss
  app/frontend/styles/navbar.scss
  app/frontend/styles/nous-rejoindre.scss
  app/frontend/styles/outils.scss
  app/frontend/styles/parlent-de-nous.scss
  app/frontend/styles/qui-fait-quoi.scss
  app/frontend/styles/recompenses.scss
  app/frontend/styles/rem.scss
  app/templates/layout.html
  app/templates/new-home.html
  app/templates/sonum-banner-carto.html
  app/templates/spa.html
  app/views.py
Labels: codeReview

#56 J carto
  app/config_app/config_app_data_endpoints.py
  app/config_app/config_app_global.py
  app/config_app/config_app_navbar.py
  app/config_app/config_app_routes.py
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/scripts/components/CISSearchResultsCountAndTabs.vue
  app/frontend/scripts/components/DynamicBanner.vue
  app/frontend/scripts/components/DynamicDetail.vue
  app/frontend/scripts/components/SearchResultsMap.vue
  app/frontend/scripts/components/screens/DynamicScreen.vue
  app/frontend/scripts/constants.js
  app/frontend/scripts/store/actions.js
  app/frontend/scripts/store/getters.js
  app/frontend/scripts/store/mutations.js
  app/frontend/scripts/store/store.js
  app/frontend/scripts/utils.js
  app/templates/spa.html
Labels: codeReview

#57 J endcarto
  app/config_app/config_app_data_endpoints.py
  app/config_app/config_app_footer.py
  app/config_app/config_app_navbar.py
  app/frontend/scripts/components/Brand.vue
  app/frontend/scripts/components/DynamicDetail.vue
  app/frontend/scripts/components/DynamicMap.vue
  app/frontend/scripts/components/DynamicStaticRaw.vue
  app/frontend/scripts/components/NavBar.vue
  app/frontend/scripts/components/SearchResultsMap.vue
  app/frontend/scripts/components/screens/DynamicScreen.vue
  app/frontend/scripts/config/api.js
  app/frontend/scripts/store/actions.js
  app/frontend/scripts/store/mutations.js
  app/frontend/scripts/store/store.js
  app/frontend/scripts/utils.js
  app/templates/spa.html
Labels: codeReview
